### ISSUE TITLE
Timestamp of the image

### ISSUE THREAD

**Issue by seekjjj1** [yellow07200/ESD_labeling_tool#2]
I want to synthesise event frames corresponding to RGB images using raw event data, where do I get the timestamps corresponding to RGB images?

**Comment by yellow07200** [comment]
Hi @seekjjj1 ,

You can find in line 104-105 in _labeling_auto_clean_2.m_ [here](https://github.com/yellow07200/ESD_labeling_tool/blob/6253feab45063537e6ba52d1efdf166d2438a4a2/labeling_auto_clean_2.m#L104C5-L105C71)

**Comment by seekjjj1** [comment]
Thank you for patiently answering my questions.
